CREATE TABLE [dbo].[City](
	[Id] [uniqueidentifier] NOT NULL,
	[Ibge] [numeric](7) NOT NULL,
	[UF] [varchar](2) NOT NULL,
	[NameCity] [nvarchar](256) NOT NULL,
	[Latitude] [nvarchar](256) NOT NULL,
	[Longitude] [varchar](256) NOT NULL,
	[Region] [nvarchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Ibge] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[City] ADD  DEFAULT (newid()) FOR [ID]
